name: Check Version Against NPM

on:
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run version check script
        run: deno run --allow-net --allow-read scripts/check-version.ts
