name: Publishing Package to NPM

on:
  push:
    branches:
      - publish

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
      # checkout the code
      - uses: actions/checkout@v4

      # install node
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # install pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.11
          run_install: false
      
      # install dependencies
      - run: pnpm install --frozen-lockfile

      # run tests
      - run: pnpm run test

      # publishing the package to npm
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
