name: Run Tests

on:
  push:
    branches-ignore:
      - 'publish'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      
      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      # Install pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: '8.x'
          run_install: true

      # Run tests
      - run: pnpm run test
